### ISSUE TITLE
Support EDTF from ISO 8601 draft

### ISSUE THREAD

**Issue by rettinghaus** [saw-leipzig/csv2cmi#18]
To enter multiple dates and/or intervals the *Extended Date/Time Format* should be supported.
https://www.loc.gov/standards/datetime/pre-submission.html#extendedintervall1

**Comment by rettinghaus** [comment]
#20 brings some EDTF features.

**Comment by zed-g** [comment]
As a reminder in case @jadolan takes a stab at this: Have you thought about using <https://github.com/ixc/python-edtf> for parsing edtf-based dates?

**Comment by rettinghaus** [comment]
Check out the develop-module branch @zed-g. There I startet working on integrating python-edtf. 
Still some problems: we need to detect edtf and convert it to (classic) iso format or w3c compatible string. AFAICS the main work still is on us. 
If you have any cunning ideas, please let me know.

See:
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.datable.w3c.html
http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.datable.iso.html

**Comment by zed-g** [comment]
I looked at the specification for EDTF at <https://www.loc.gov/standards/datetime/edtf.html> and found it was just updated and finalized in October. `python-edtf` is not up to date with the newest version, the relevant issue is ixc/python-edtf#24. I don't think it makes sense to implement this without the underlying parser complying to the current version of EDTF.

> Still some problems: we need to detect edtf

Maybe it's easiest to just handle this via a command line flag and processing all dates as edtf if the flag is set? Could be `--edtf-dates` or something like that?

**Comment by rettinghaus** [comment]
#31 now features all relevant cases.
