### ISSUE TITLE
use name tag as default

### ISSUE THREAD

**Issue by rettinghaus** [saw-leipzig/csv2cmi#23]
When there is no authority file id given, set default tag for correspondent to `<name>` instead of `<persName>`.

see: TEI-Correspondence-SIG/CMIF/issues/18

**Comment by peterstadler** [comment]
That sounds reasonable to me (motivated by https://github.com/TEI-Correspondence-SIG/CMIF/issues/18#issuecomment-460780937 )

**Comment by rettinghaus** [comment]
fixed with #35
