### ISSUE TITLE
support various senders/addressees

### ISSUE THREAD

**Issue by jadolan** [saw-leipzig/csv2cmi#25]
It could be useful to allow various correspondents of the same type, since many letters have more than one sender or addressee. A possible way of handling them could be a special character as a delimiter within the cell. See the following example:

`sender,senderID,senderPlace,senderPlaceID,senderDate,addressee,addresseeID,addresseePlace,addresseePlaceID,edition,key,note
Johann Sebastian Bach|Maria Barbara Bach,http://viaf.org/viaf/12304462|http://viaf.org/viaf/45361994,Leipzig,http://www.geonames.org/2879139,1730-10-28,Georg Erdmann,http://viaf.org/viaf/3264804,Danzig,http://www.geonames.org/3099434,"Bach-Dokumente Bd. 1, Leipzig 1963",23,four years later`

**Comment by zed-g** [comment]
We have a real need for this ath the BBAW and given a CSV as suggested by @jadolan:

```csv
sender,senderID,senderPlace,senderPlaceID,senderDate,addressee,addresseeID,addresseePlace,addresseePlaceID,edition,key,note
Johann Sebastian Bach|Maria Barbara Bach,http://viaf.org/viaf/12304462|http://viaf.org/viaf/45361994,Leipzig,http://www.geonames.org/2879139,1730-10-28,Georg Erdmann,http://viaf.org/viaf/3264804,Danzig,http://www.geonames.org/3099434,"Bach-Dokumente Bd. 1, Leipzig 1963",23,four years later
```

with the `|` symbol as a delimiter @jadolan would probably add a function wich parses both the sender and adressee field (as well as the ID fields) and feeds into https://github.com/saw-leipzig/csv2cmi/blob/947dd7644fa814fc5dded367539b50630d4bc7d2/csv2cmi.py#L393 and https://github.com/saw-leipzig/csv2cmi/blob/947dd7644fa814fc5dded367539b50630d4bc7d2/csv2cmi.py#L415.

Is this something you would adopt for `csv2cmi`? If you think the delimiter could break existing CSVs, we could either add some way to escape the delimiter (i. e. `\|` doesn't split the field) or only explicitly enable the delimiter via an option in `csv2cmi.ini`.

**Comment by ukretschmer** [comment]
In contrast to the extra delimiter approach I'd like to suggest a general multiline dataset support. I know it also has it's pros and cons, but I think in terms of user handling and data consistency it could be the better way.

So imagine storing additional values in additional lines, hold together by `edition` and `key`. A CSV with 3 senders and 2 adressees could look like this:
```
sender,senderID,senderPlace,senderPlaceID,senderDate,addressee,addresseeID,addresseePlace,addresseePlaceID,edition,key,note
Johann Sebastian Bach,http://viaf.org/viaf/12304462,Leipzig,http://www.geonames.org/2879139,1730-10-28,Georg Erdmann,http://viaf.org/viaf/3264804,Danzig,http://www.geonames.org/3099434,"Bach-Dokumente Bd. 1, Leipzig 1963",23,four years later
Second Sender,http://viaf.org/viaf/12345S2,,,,Second Adressee,http://viaf.org/viaf/12345XXX,,,"Bach-Dokumente Bd. 1, Leipzig 1963",23,
Third Sender,http://viaf.org/viaf/12345S3,,,,,,,,"Bach-Dokumente Bd. 1, Leipzig 1963",23,
```
Order of persons or places is the order of appearance in lines.

What do You tinhk?

**Comment by zed-g** [comment]
In my experience multiline datasets in tables/CSVs are hard to get right and in our case, we don't have a key for every letter (as they are not numbered in the edition we are working on). Generally I think you can either "overload" a table field with multiple values seperated by a delimiter or work with keys/IDs which bind data from multiple lines together. It's a tradeoff between a simply looping over all lines and having to parse the data fields in some cases vs. first parsing all the lines and establishing relationships via `edition` and `key` for every entry.

All in all I still would prefer the approach of having all the data in one line and using a delimiter but maybe @jadolan can weigh in after she has gained more insight implementing our use case.

**Comment by rettinghaus** [comment]
@zed-g is right. Trying to merge something together due processing is something awful, especially if the data is not completely consistent. Imagine a footer on a letter by another person than the original writer with a separate date (and without a `key`). One could argue that there are always special cases and it lays within the responsibility of the user. But keeping the mess inside a single line to minimal level and keep track of ordering is too. 
Another option would be indeed to introduce user IDs in an extra column, which would contradict the original simple straight-foreword approach of the app.

**Comment by zed-g** [comment]
@jadolan has made great progress with the delimiter-based approach and has it mostly working. She should be able to provide a pull request soon. At least our use case is handled fine that way and I'd say it should be quite usable for others as well.

**Comment by zed-g** [comment]
See PR #27 by @jadolan...

**Comment by rettinghaus** [comment]
PR merged
