### ISSUE TITLE
switch from ini to json

### ISSUE THREAD

**Issue by rettinghaus** [saw-leipzig/csv2cmi#28]
Wouldn't it be better to have additional meta data for configuration stored in a json file instead an ini file?

**Comment by rettinghaus** [comment]
What do you think @arockenberger, @jadolan and @zed-g?

**Comment by zed-g** [comment]
I don't think that's necessary. The INI file works fine and is more easily editable by hand than JSON.

**Comment by rettinghaus** [comment]
closing for now
