### ISSUE TITLE
Use textual date information?

### ISSUE THREAD

**Issue by ukretschmer** [saw-leipzig/csv2cmi#40]
In addition to the technical date information, extracted from `senderDate` or `addresseeDate` and represented in corresponding attributes of the `date` element, it would be nice to use textual content for the `date` element, instead of leaving it empty, if there is such information within the CSV file, e.g. in columns labeled as `senderDateText` and `addresseeDateText`. 

This would enable representations like
```xml
<date notBefore="1767-12-21" notAfter="1768-01-10">Ende Dezember 1767 oder Anfang Januar 1768</date>
```

**Comment by rettinghaus** [comment]
implemented with #45
