### ISSUE TITLE
Supporting multiple projects

### ISSUE THREAD

**Issue by ukretschmer** [saw-leipzig/csv2cmi#42]
It would be good to have an option to choose the output path and/or the path of the ini file, to better support projectspecific settings, e.g.:

- projectfolder1
-- input.csv
-- csv2cmi.ini
-- output.xml
- projectfolder2
-- input.csv
-- output.xml

**Comment by rettinghaus** [comment]
output file option added with 4f75526358f2cabb95f30c12011931fe1339ce2e
