### ISSUE TITLE
Bibliography replacement

### ISSUE THREAD

**Issue by ukretschmer** [saw-leipzig/csv2cmi#43]
It would be nice to have a mechanism implemented, which replaces used edition short titles in CSV file by configured (ini file) full titles.

Example:

Used short title: JBW1, JBW2

ini file part:
```ini
[Bibliography]
JBW1 = Jabobi Briefwechsel, Band 1, usw.
JBW2 = Jabobi Briefwechsel, Band 2, usw.
```

**Comment by ukretschmer** [comment]
Thinking a little bit over this I got to the point, that it might be the best way to try to match short titles against config sections, which have the same architecture like `[Edition]` so that I can configure either type and full title of my bibliographic record. 

Adopting from the above example (short titles: JBW1, JBW2), the config file would look like:
```ini
[JBW1]
title = Jabobi Briefwechsel, Band 1, usw.
type = print

[JBW2]
title = Jabobi Briefwechsel, Band 2, usw.
type = print
```

**Comment by rettinghaus** [comment]
I'm not totally convinced by this approach. 
The question is then: why put this information into the INI file, and not into a more suitable file, like bibTeX? Or just search/replace them in your input file?
