### ISSUE TITLE
Examples does not work in CMIF Creator

### ISSUE THREAD

**Issue by yurj** [saw-leipzig/csv2cmi#65]
Hi!

 running `python csv2cmi.py examples/Example.csv` and uploading `examples/Example.xml` in https://correspsearch.net/en/cmif-creator.html, the tool returns various errors and does not parse correctly the correspondences.

![cmif-creator](https://github.com/saw-leipzig/csv2cmi/assets/1100944/42594c69-e0cd-495d-93fc-ccd00675d93f)

I've several other example of csv not working. I've been able to modify csv2cmi.py to create a cmif files which validates in CMIF Creator.

My question is: starting from a csv, should I use `csv2cmi` or it must validate on CMIF Creator, before sending it to correspSearch?

BTW, it is not clear if correspSearch accept only CMIF files or the csv is enough.

Thanks!

**Comment by rettinghaus** [comment]
This project is not connected to @correspSearch and the generated XML files are not suitable for use in the CMIF-Creator. 

Please raise an issue at https://github.com/correspSearch/CMIF-Creator or contact the website maintainer.
